### ISSUE TITLE
/validate command don't work as desired

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes-sigs/contributor-tweets#101]
After making any changes to the issue labelled `kind/tweet` we need to run ` /validate` command to update the related PR, but it doesn't seem to work as desired.
It's related to this https://github.com/kubernetes-sigs/contributor-tweets/issues/83#issuecomment-918520748 & https://github.com/kubernetes-sigs/contributor-tweets/issues/89. 

cc @gkarthiks

**Comment by Atharva-Shinde** [comment]
its working for me here #102  #93

**Comment by Debanitrkl** [comment]
Yeah worked for me too but wasn't working for the mentioned issues. It's weird but don't know why it's happening so

**Comment by gkarthiks** [comment]
let me take a look at https://github.com/kubernetes-sigs/contributor-tweets/issues/89 and circle back.

**Comment by Debanitrkl** [comment]
fixed 
/close
