### ISSUE TITLE
Tweet about processes for creating and sharing surveys in the community

### ISSUE THREAD

**Issue by sreekaransrinath** [kubernetes-sigs/contributor-tweets#116]
Hey contributors! Thinking of getting some feedback from the community in the form of surveys? 

We have an official process with regulatory requirements for surveying K8s contributors.

We also have resources to help. Check it out!

https://www.kubernetes.dev/resources/services/#surveys

Requirements for surveying the community were brought up in the 12th Nov 2021 SIG ContribEx Weekly Marketing Meeting.

**Comment by sreekaransrinath** [comment]
![image](https://user-images.githubusercontent.com/50989977/141505114-1e0da376-9aa4-42c4-b8d2-253a7dcfc1b0.png)

While it's 7 characters over the limit, it does fit in, and I was able to tweet it as a test. I believe the characters in the link would be shortened once twitter puts it through its link-shortening system. We should be good to go.

**Comment by sreekaransrinath** [comment]
@chris-short an official k8s shortener url would be helpful in cases like these. k8s.io maybe?

**Comment by sreekaransrinath** [comment]
If it's not yet a thing, I'd be happy to help build it out

**Comment by chris-short** [comment]
Oh it's a thing: [https://github.com/kubernetes/k8s.io/tree/main/apps/k8s-io](https://github.com/kubernetes/k8s.io/tree/main/apps/k8s-io)

Let me know if you'd like me to handle this. But, if you're comfortable, feel free.
