### ISSUE TITLE
Tweet: Migrating to the new mailing list

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes-sigs/contributor-tweets#138]
**Provide the actual tweet content between the commented colons**

ICYMI: The primary Kubernetes contributor mailing list has been migrated to a new address as of January 2, 2022: https://groups.google.com/a/kubernetes.io/g/dev. All members have already been migrated to the new mailing list, there’s no need to resubscribe.

**Comment by parispittman** [comment]
could we do something less wordy since its twitter and also cut the date? something like -

The contributor mailing list has been migrated dev@kubernetes.io. Everyone has been migrated from the old list; there's no need to resubscribe.
