### ISSUE TITLE
Disable github actions for twitter-together on forked repos

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes-sigs/contributor-tweets#14]

**Comment by kaslin** [comment]
Didn't you do this a while ago? So it can be closed, right?

**Comment by rajula96reddy** [comment]
This is a bit different I guess. The github-action is trying to tweet on some of the rebased commits on forked repos. Like [this](https://github.com/rajula96reddy/contributor-tweets/runs/1090496410). I will take a look again and fix this
