### ISSUE TITLE
ReleaseTeamSurvey Tweet1 2022

### ISSUE THREAD

**Issue by kaslin** [kubernetes-sigs/contributor-tweets#150]
Attempting to create a new tweet to promote the end of cycle survey for the release team. We should tweet about this repeatedly, especially more toward the end of the cycle.

If you are a member of the release team, please keep an eye out for the end of cycle survey as the cycle come to a close! Your feedback about your experience as a member of the release team is valuable, and the team would appreciate your feedback.

**Comment by chris-short** [comment]
@reylejano The day you send the report is when we should send this.

**Comment by jeremyrickard** [comment]
I think it makes sense to do this probably around the time we send the survey. However, we already remind folks in the release team meetings and via email, is a tweet going to be more targeted than those avenues?

**Comment by chris-short** [comment]
Paris says (and I agree hence why I'm quoting), "It feels like half our audience gets their info from email and the other half gets it through social media."

I believe the dockershim debacle is a clear example of that. So, with all that being said, yes, I think it smart to tweet, in general.

But, it really depends on who is the target. If it's contributors, this is the right place and method. If it's a specific group of contributors, whatever methods of communication you've used that have worked should continue to be used and maybe not a tweet. But, it's the release teams' call.

**Comment by chris-short** [comment]
Oh... We also have a mass message Slack tool if you need to message out to multiple channels at once. We can use that too.

**Comment by Debanitrkl** [comment]
@kaslin midcycle survey is out, we could have a tweet on that
