### ISSUE TITLE
[Request for New Tweet] WG Naming tweet request

### ISSUE THREAD

**Issue by gkarthiks** [kubernetes-sigs/contributor-tweets#16]
## Tweet content:
```
Looking for a way to make K8s better? Join WG Naming and contribute to naming conventions, and inclusive language! (https://bit.ly/35TWwIO)
```

## Tweet time:
Please wait for the approval from @celestehorgan @jdumars @justaugustus @zacharysarah

## Urgency: Medium

/cc @kaslin

**Comment by celestehorgan** [comment]
/approve

(if that doesn't work, LGTM!)

**Comment by gkarthiks** [comment]
Update: removed `documentation clarity` as per @justaugustus comment.

**Comment by kaslin** [comment]
@gkarthiks Did you get the lgtm's you were looking for or are you still waiting on a couple more?

**Comment by gkarthiks** [comment]
@kaslin I got the lgtm, but we want to tweet this during first week of October. So created a PR and left it in hold for now.

**Comment by justaugustus** [comment]
> Looking for a way to make #Kubernetes better? Join WG Naming and contribute to the discussion on inclusive language and naming conventions! (https://bit.ly/35TWwIO)

Let's do this ^^
- spell out Kubernetes and use the hashtag
- drop the Oxford comma

**Comment by justaugustus** [comment]
(I'll comment on the PR)

**Comment by kaslin** [comment]
Gotcha, yeah the timing thing can be a challenge. I'll set myself a reminder to check back in on that in the first week of October then. This is looking good, thanks for leading the charge to get it ready to go! 👍
