### ISSUE TITLE
Add Kubernetes 1.25 Shadow App Open Tweet

### ISSUE THREAD

**Issue by reylejano** [kubernetes-sigs/contributor-tweets#170]
**Provide the actual tweet content between the commented colons**

The Kubernetes v1.25 Release Team shadow application is now open until April 29
https://forms.gle/X9R3SjToUyb5BqAi9

**Comment by jeremyrickard** [comment]
/retitle Add Kubernetes 1.24 Shadow App Open Tweet

**Comment by jeremyrickard** [comment]
/retitle Add Kubernetes 1.25 Shadow App Open Tweet

**Comment by jeremyrickard** [comment]
ooops.... it's 1.25 :) 

/honk

**Comment by kaslin** [comment]
There was a spacing issue, so I sent it but then deleted it and replaced it with fixed spacing: https://twitter.com/K8sContributors/status/1515022814528516100
