### ISSUE TITLE
Add Kubernetes 1.24 Shadow App Extended Tweet

### ISSUE THREAD

**Issue by reylejano** [kubernetes-sigs/contributor-tweets#177]
**Provide the actual tweet content between the commented colons**

The Kubernetes v1.25 Release Team shadow application is extended to May 6.
The #Kubernetes Release Team is a great way to start contributing to the @kubernetesio project.
https://forms.gle/X9R3SjToUyb5BqAi9

**Comment by jeremyrickard** [comment]
👍
