### ISSUE TITLE
annual report summary broadcast 

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-tweets#195]
**Provide the actual tweet content between the commented colons**

Kubernetes Annual Report Summary 2021 is now live! Calling our 70k contributors, participating co's,& new contributors: attn to Help Wanted section! Celebrate with us in the accolades&read our themes! RT
https://k8s.io/blog/2022/06/01/annual-report-summary-2021/

**Comment by dims** [comment]
LGTM
