### ISSUE TITLE
Update the broken links

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes-sigs/contributor-tweets#197]
In the README.md file of this repo there are few broken links that needs to be updated with the new ones

- [ ] Under the **Kubernetes Contributor Tweets** section :
> ... This project is currently owned and maintained by the [SIG Contribex Marketing Team](https://github.com/kubernetes/community/tree/main/communication/marketing-team).

- [ ] Under the **Contribute** section:
> ... Please feel free to join our [weekly meetings](https://github.com/kubernetes/community/tree/main/sig-contributor-experience#community-management) or reach out to the maintainers of this project.

**Comment by ssavi-ict** [comment]
Hello @Atharva-Shinde, I am here to see the tag "_good first issue_". I have a little knowledge about Open Source Contribution. However, I was trying to figure out WHICH link to replace the mentioned [SIG Contribex Marketing Team](https://github.com/kubernetes/community/tree/main/communication/marketing-team) link. 

Seems like I am not able to get it. Could you please help me to mention which link to replace with? 
Also, I tried to access the _weekly meeting_ link. Seems like it is enabled for allowed people only. 

Your help is appreciated.

**Comment by Atharva-Shinde** [comment]
hey @ssavi-ict 

> Will the mentioned link be replaced with [this one](https://github.com/kubernetes/community/tree/master/communication/marketing-team) ?

Yes! 

And you can find the meeting link [here](https://github.com/kubernetes/community/tree/master/sig-contributor-experience#contributor-comms) under contributor-comms meetings section :) (it's accessible to everyone!)
This is the meeting url  https://zoom.us/j/596959769?pwd=TURBNlZPb3BEWVFmbWlCYXlMVVJiUT09

**Comment by ssavi-ict** [comment]
Hi, @Atharva-Shinde I have initiated PR #199 . Please review it at your feasible time. 
Thank you.
