### ISSUE TITLE
Kubernetes office hours announcement for June 2022

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/contributor-tweets#202]
**Provide the actual tweet content between the commented colons**

Don't miss #Kubernetes office hours this Wednesday
This month's guest is @dims, joining our host @csantanapr to talk about SIG K8s Infra
https://www.youtube.com/watch?v=T_hRSyAFS8A

Send as soon as possible, Today (Monday June 13th) or tomorrow (Tuesday 14th)

**Comment by Atharva-Shinde** [comment]
done!
/close
