### ISSUE TITLE
Want to be a contributor of Kubernetes Project

### ISSUE THREAD

**Issue by paulohgontijoo** [kubernetes-sigs/contributor-tweets#207]
Hello, people! I am a Software Engineer student, new here and want to contribute with Kubernetes Projects.

**Comment by Debanitrkl** [comment]
Hi  @paulohgontijoo thanks for your interest but raising an github issue is not the correct way to begin with, please go through the [contributor guide](https://www.kubernetes.dev/docs/guide/) for more information.
