### ISSUE TITLE
2021 Anual Report: intro tweet

### ISSUE THREAD

**Issue by fsmunoz** [kubernetes-sigs/contributor-tweets#214]
**Provide the actual tweet content between the commented colons**

In 2021 we had a lot of improvements in Kubernetes: find many of them and much more on our recently published 2021 Annual Report! https://github.com/kubernetes/steering/blob/main/reports/summary-2021.md

**Comment by debacm** [comment]
https://twitter.com/K8sContributors/status/1532429719777443840?s=20&t=bpSj0UrMSXhvZQOuOsi0Gg, this tweet is already posted.

**Comment by Debanitrkl** [comment]
https://twitter.com/K8sContributors/status/1532429719777443840?s=20&t=bGVZFJ7VvQR2NUhIoopI_Q, sorry but this tweet is already done.
