### ISSUE TITLE
Kubernetes office hours announcement for July 2022

### ISSUE THREAD

**Issue by csantanapr** [kubernetes-sigs/contributor-tweets#236]
**Provide the actual tweet content between the commented colons**

Don't miss #Kubernetes office hours today
This month's guests are @reylejano and @PuDiJoglekar, joining our host @csantanapr to talk about SIG Security
https://www.youtube.com/watch?v=7eTEXSawbm4

I totally forgot about this tweet, can we tweet this today Wednesday July 20th before 8AM PST
cc @chris-short

**Comment by Atharva-Shinde** [comment]
closing the issue as the meeting happened on 20th of July.
/close
