### ISSUE TITLE
Tweet regarding meet our contributor blog post 

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes-sigs/contributor-tweets#253]
**Provide the actual tweet content between the commented colons**

#ICYMI Here's a blog post on a few of the many active kubernetes contributors from China region, read to know more about their experience as a contributor and how they have helped the project grow, https://www.k8s.dev/blog/2022/08/15/meet-our-contributors-china-ep-03/

**Comment by Atharva-Shinde** [comment]
trying after the fix #273

**Comment by Atharva-Shinde** [comment]
trying after the potential fix #273

**Comment by Atharva-Shinde** [comment]
trying after potential fix at #273
