### ISSUE TITLE
1.26 Enhancements Board Update

### ISSUE THREAD

**Issue by gracenng** [kubernetes-sigs/contributor-tweets#263]
**Provide the actual tweet content between the commented colons**

🚧 Changes to the v1.26 release opt-in process 🚧

The enhancements sheet with be replaced with an automated Github board.  SIG lead only, apply `lead-opt-in` label on KEPs to opt-in.

Find us on Slack at release-enhancements for help!

cc @reylejano @rhockenbury @leonardpahlke

**Comment by gracenng** [comment]
Enhancements tracking migration: https://github.com/kubernetes/sig-release/issues/2009

**Comment by reylejano** [comment]
@gracenng 
I think there is a typo:

> 🚧 Changes to the v1.26 release opt-in process 🚧
> 
> The enhancements sheet <strike>with</strike> will be replaced with an automated Github board. SIG lead only, apply lead-opt-in label on KEPs to opt-in.

**Comment by reylejano** [comment]
(non-blocking) Also suggest something like:

📣 Changes to the v1.26 release enhancements opt-in process 📣 
For 1.26, the enhancements sheet is replaced with a Github projects board. 
To opt-in for 1.26, SIG leads apply the `lead-opt-in` label on the KEP issue.

/cc @palnabarun @rhockenbury @leonardpahlke @gracenng

**Comment by leonardpahlke** [comment]
I like this suggestion. I would send the tweet out after we send the email. Then we could include a link in the email that gives more details.
