### ISSUE TITLE
Testing Validate Command after #273 merged

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes-sigs/contributor-tweets#274]
**Provide the actual tweet content between the commented colons**

This is a test TweetThis is a test Tweet

https://github.com/kubernetes-sigs/contributor-tweets/issues/274#tasklist-block-55f904ee-97ea-4169-afd0-098f2e9da2c2

**Comment by Atharva-Shinde** [comment]
the job was skipped for some reason

**Comment by Atharva-Shinde** [comment]
worked! now with exceeding char limit tweet

**Comment by Atharva-Shinde** [comment]
great!
now changing back and validating

**Comment by Atharva-Shinde** [comment]
I cross-checked on my fork just wanted to surface it here

**Comment by Atharva-Shinde** [comment]
I had cross-checked on my fork
1. Now a tweet PR isn't automatically generated unless we `/validate` on a Issue
2. It's still not working as expected

**Comment by Atharva-Shinde** [comment]
I had cross-checked on my fork just wanted to re-surface it here
1. Now a tweet PR isn't automatically generated unless we `/validate` on a Issue
2. It's still not working as expected

**Comment by Atharva-Shinde** [comment]
I had cross-checked on my fork and wanted to re-surface it here
1. Now a tweet PR isn't automatically generated unless we `/validate` on a Issue
2. It's still not working as expected

**Comment by Atharva-Shinde** [comment]
I had cross-checked on my fork and wanted to re-surface it here
1. Now a tweet PR isn't automatically generated unless we `/validate` on an issue
2. It's still not working as expected

**Comment by Atharva-Shinde** [comment]
ref: https://github.com/Atharva-Shinde/contributor-tweets/issues/5

**Comment by Atharva-Shinde** [comment]
I've made few changes and its working here ref: https://github.com/Atharva-Shinde/contributor-tweets/issues/5

**Comment by Atharva-Shinde** [comment]
would make a PR soon

**Comment by Atharva-Shinde** [comment]
I cross-checked on my fork and wanted to re-surface it here
1. A tweet PR isn't automatically generated unless we `/validate` on an issue
2. It's still not working as expected on this repo not even once (if its supposed to be working sporadically)
3. But is totally working on my fork. Always.
ref: with changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/19)
without changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/21)

**Comment by Atharva-Shinde** [comment]
I cross-checked on my fork and wanted to re-surface it here
1. With #273 merged, now a tweet PR isn't automatically generated unless we `/validate` on an issue
2. It's still not working as expected on this repo not even once (if its supposed to be working sporadically)
3. But is totally working on my fork. Always.
ref: with changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/19)
without changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/21)

**Comment by Atharva-Shinde** [comment]
I cross-checked on my fork and wanted to re-surface it here
1. With #273 merged, now a tweet PR isn't automatically generated unless we `/validate` on an issue
2. It's still not working as expected on this repo
3. But is totally working on my fork. Always.
ref: with changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/19)
without changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/21)

**Comment by Atharva-Shinde** [comment]
I cross-checked on my fork and wanted to re-surface it here. 
1. With #273 merged, now a tweet PR isn't automatically generated unless we `/validate` on an issue 
2. It's still not working as expected on this repo.
3. But is totally working on my fork. Always.
ref: with changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/19)
without changes of [#273](#273):- [here](https://github.com/Atharva-Shinde/contributor-tweets/issues/21)

**Comment by chris-short** [comment]
@Atharva-Shinde We should probably setup some time to look into this together. More eyes are better usually. With KubeCon upon us, this week and next are pretty much toast (unless you're going to be in town).

**Comment by Atharva-Shinde** [comment]
I Agree @chris-short ! Just wanted to get the ball rolling as it's been hanging around for a long time now. IMO this Issue could be the test issue to test our workflow so that there's no need to wait for creating new tweet issue every time we want to test the workflow. I've also setup an [issue](https://github.com/kubernetes-sigs/contributor-tweets/issues/278) so that we can keep track of this in one place. 
Although I'm in full support of closing this issue if it's just getting redundant by time and isn't adding any value.

Feedbacks welcome :)

**Comment by imnmo** [comment]
@chris-short @Atharva-Shinde this merge didn't solve the problem and I see new file changes after the merge. See here:

**Comment by imnmo** [comment]
/close 

see here https://github.com/kubernetes-sigs/contributor-tweets/issues/289
