### ISSUE TITLE
Validate command not working as desired

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes-sigs/contributor-tweets#278]
Expected behaviour: 
When a tweet within character-limit is created in an Issue, an automated PR from GitHub-action bot is created. Now if the author updates the Issue description with some new changes in the tweet, they should comment `/validate` to validate it again. If the tweet is within character limit, it will trigger the workflow and the bot will update the PR with the new tweet.

Current behaviour:
The tweet PR isn't getting updated with the new changes done by author in tweet description even though they use `/validate` command.

- Issue #274 
- Issue #253 
- Issue #222 
- Issue #218

References to jobs:
Job Error: The process '/usr/bin/git' failed with exit code 1
https://github.com/kubernetes-sigs/contributor-tweets/actions/runs/3255451191/jobs/5344780842#step:6:515
https://github.com/kubernetes-sigs/contributor-tweets/actions/runs/2873883155/jobs/4561871980#step:6:515

**Comment by Atharva-Shinde** [comment]
We could try updating GitHub actions(github/checkout, actions/setup-node and twitter-together/action) and node of our workflow to the latest versions, as node 12 is deprecated and also the actions we are using in this workflow supports node 16.

**Comment by Atharva-Shinde** [comment]
We could try updating GitHub actions(actions/checkout, actions/setup-node and twitter-together/action) and node of our workflow to the latest versions, as node 12 is deprecated and also the actions we are using in this workflow supports node 16. ref: https://github.com/actions/checkout/issues/417

**Comment by imnmo** [comment]
Thanks for the findings @Atharva-Shinde  
To clarify: the job is failing due to a dependency error (latest node 12). Hence, the expected behavior for updating tweets is not happening?

**Comment by Atharva-Shinde** [comment]
actions/checkout@v2 had some bugs with tokens and now with node 12 being deprecated, updating the workflow to latest versions can be a first step towards fixing the command if not being the only reason to fail the job :)
Also do refer to this [comment](https://github.com/kubernetes-sigs/contributor-tweets/issues/274#issuecomment-1279780721 ) I made while testing

**Comment by Atharva-Shinde** [comment]
actions/checkout@v2 had some bugs with tokens and now with node 12 being deprecated, updating the workflow to latest versions can be a first step towards fixing the command if not being the only reason causing the failure of jobs :)
Also do refer to this [comment](https://github.com/kubernetes-sigs/contributor-tweets/issues/274#issuecomment-1279780721 ) I made while testing

**Comment by imnmo** [comment]
I observed this strange behavior a while ago. Let's see with node upgrade things go better

**Comment by imnmo** [comment]
@Atharva-Shinde https://github.com/kubernetes-sigs/contributor-tweets/issues/278 merge didn't solve the problem and I see new file changes after the merge. See here: https://github.com/kubernetes-sigs/contributor-tweets/pull/281/files

**Comment by Atharva-Shinde** [comment]
thats how currently the workflow **should** perform,

**Comment by Atharva-Shinde** [comment]
That is how workflow is supposed to perform and that's not where the problem is,
if you try to update the tweet issue with some new changes and `/validate` again, (in the working state) it should automatically update your pr with new changes, and this is where the error occurs, in current state it is not updating PR with newest change that the author makes.

**Comment by Atharva-Shinde** [comment]
@imnmo That is how workflow is supposed to perform and that's not where the problem is,
if you try to update the tweet issue with some new changes and `/validate` again, (in the working state) it should automatically update your pr with new changes, and this is where the error occurs, in current state it is not updating PR with newest change that the author makes.

**Comment by Atharva-Shinde** [comment]
@imnmo That is how workflow is supposed to perform and that's not where the problem is,
if you try to update the tweet issue with some new changes and `/validate` again, (in the working state) it should automatically update your pr with new changes, and this is where the error occurs (or was occurring).

So try changing your tweet issue and lets see if its working or is still broken

**Comment by imnmo** [comment]
/close 

see here https://github.com/kubernetes-sigs/contributor-tweets/issues/289
