### ISSUE TITLE
twitter-together action skipping jobs

### ISSUE THREAD

**Issue by chris-short** [kubernetes-sigs/contributor-tweets#285]
It looks like the twitter-together action hasn't run since [being updated recently](https://github.com/kubernetes-sigs/contributor-tweets/commit/d00ea2309388dcfbc1e075dd38b877b90d4bbc3a).

Since [Twitter recently shut off third party clients](https://arstechnica.com/tech-policy/2023/01/reports-twitters-third-party-client-lockout-is-intentional/), I checked the K8sContributors Developer Portal and our "app" is still present but whether or not it's still functional is a different question.

My first suggestion is rolling back these changes then testing them one by one to see if they work. Feel free to add me to any test issues or PRs. Please flag PRs with the `hold` label and mention it's a test.

**Comment by imnmo** [comment]
@AvineshTripathi feel free to reach me Incase of any help.

**Comment by Atharva-Shinde** [comment]
I addressed this issue in our weekly meeting, but am commenting here for better visibility.

Bumping up the version isn’t causing the skipping of jobs, it is this PR that changed the workflow: https://github.com/kubernetes-sigs/contributor-tweets/pull/273
So to avoid jobs from skipping we need to rollback to changes of the above PR.

**Comment by imnmo** [comment]
This tracking issue should cover the upcoming discussions: https://github.com/kubernetes-sigs/contributor-tweets/issues/289

**Comment by imnmo** [comment]
/close

see here: https://github.com/kubernetes-sigs/contributor-tweets/issues/289
