### ISSUE TITLE
Tracking Issue for Zapier Automation of GitHub to Twitter

### ISSUE THREAD

**Issue by Atharva-Shinde** [kubernetes-sigs/contributor-tweets#289]
This issue is created to address and discuss the ongoing effort of building a new tweet automated solution using Zapier.

**Comment by Atharva-Shinde** [comment]
The Zapier automation could be a good replacement to our current [contributor-tweets automation](https://github.com/kubernetes-sigs/contributor-tweets)

**Comment by Atharva-Shinde** [comment]
The Zapier automation could be a good replacement to our current [contributor-tweets automation](https://github.com/kubernetes-sigs/contributor-tweets)

**Comment by imnmo** [comment]
Should existing workflow remain the same: Issue to PR to tweet and PR to tweet (to be discussed). 

Existing features in the current code are : 
- Zapier automation should run based on the specific issue label
- Tweet content length should be checked (follow max tweet length)

**Comment by imnmo** [comment]
some points from our weekly comms meeting
- Editing for tweets be considered 
- Favoured is PR to tweet and close the issue

**Comment by chris-short** [comment]
Zapier account created (by @mrbobbytables)

YouTube plugged in

Still need GDrive and Zoom connections and migration can be completed.

**Comment by chris-short** [comment]
I need to start looking into a new GitHub -> Zap -> Buffer workflow.

**Comment by mrbobbytables** [comment]
Repo is being archived, going to go ahead and close this out. For more info, please see https://github.com/kubernetes/org/issues/4481

/close
