### ISSUE TITLE
Etcd Survey tweet

### ISSUE THREAD

**Issue by jberkus** [kubernetes-sigs/contributor-tweets#294]
**Provide the actual tweet content between the commented colons**

Do you use #etcd?  In #kubernetes,  outside of Kubernetes, or for something else entirely?

Etcd needs your feedback!  The Etcd project is discussing its direction and future of the project right now, and your answers will help.

https://www.surveymonkey.com/r/etcdusage23

#CloudNative

**Comment by mrbobbytables** [comment]
Repo is being archived, going to go ahead and close this out. For more info, please see https://github.com/kubernetes/org/issues/4481

/close
