### ISSUE TITLE
Test Tweet Zapier

### ISSUE THREAD

**Issue by chris-short** [kubernetes-sigs/contributor-tweets#295]
This is a test issue for use with zapier

If this is still here in 90 days, it's safe to close forever.

**Comment by chris-short** [comment]
After some initial testing with Zapier, I am not confident GitHub > Zapier > Buffer is a thing that's possible. cc @SD-13

**Comment by mrbobbytables** [comment]
Repo is being archived, going to go ahead and close this out. For more info, please see https://github.com/kubernetes/org/issues/4481

/close
