### ISSUE TITLE
Possible for tweet to embed media?

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes-sigs/contributor-tweets#31]
When using this tool, I noticed that the URL doesn't generate a "card" like it does when you tweet directly from a client. Example: 

![Screenshot from 2020-12-18 09-36-06](https://user-images.githubusercontent.com/1744971/102632297-861b0080-4114-11eb-9372-86c11d48c797.png)

Example when a card is created: 

![Screenshot from 2020-12-18 09-35-44](https://user-images.githubusercontent.com/1744971/102632332-8fa46880-4114-11eb-9173-cc032996d310.png)

Is it possible for the bot to trigger this style of URL preview? 

/assign @rajula96reddy

**Comment by rajula96reddy** [comment]
Hey! I just took a quick look into this. Seems like the card supported has to be enabled from the website through [html tags](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards) . I think our `k8s.dev` site doesn't have this support.

Try validating the `https://k8s.dev/celebration` in here https://cards-dev.twitter.com/validator


Ref: [Medium article](https://medium.com/@dinojoaocosta/how-to-make-twitter-preview-your-website-links-5b20db98ac4f)

**Comment by mbbroberg** [comment]
@rajula96reddy interesting! I don't know if that's what's happening here since the card will expand when I tweet directly but not through the tool. So I think both the site needs to have the card metadata AND the tool needs to choose whatever option is required to choose to preview it. 

Let's keep poking around Twitter together to see if they have something. (Link for new people: https://github.com/marketplace/actions/twitter-together)

**Comment by mbbroberg** [comment]
TODO list out the websites to make sure we're testing accurately.
