### ISSUE TITLE
Move from master => main as the branch name

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes-sigs/contributor-tweets#46]
We're a little out of date on that. @rajula96reddy mentioned will affect CI and should be reviewed as part of this change.

**Comment by gkarthiks** [comment]
Can we do this asap pls?

**Comment by chris-short** [comment]
Is it safe to close this?

**Comment by gkarthiks** [comment]
we haven't moved the branch from master to main yet though.

**Comment by chris-short** [comment]
Do we need to coordinate the timing of this or is it safe to do at will?

**Comment by gkarthiks** [comment]
We can do at will. All we have to do is, change the GH actions file to point the default branch as "main" from "master" once done.

**Comment by chris-short** [comment]
I'm not sure how to do that to this repo. The options aren't available to me.

Any idea @mrbobbytables @parispittman?

**Comment by mrbobbytables** [comment]
I or another repo admin can take care of renaming the branch, the [github actions](https://github.com/kubernetes-sigs/contributor-tweets/blob/master/.github/workflows/main.yml) will just have to updated `s/master/main/g`.  I'd suggest opening a PR with the changes, then we do the swap and merge the PR.

Once complete, a mail just has to be sent to the contribex mailing list stating that the branch has been renamed 👍

**Comment by gkarthiks** [comment]
I will do the PR on the actions.

**Comment by chris-short** [comment]
The Actions work is merged @mrbobbytables. I can draft an email when you're ready.

**Comment by Atharva-Shinde** [comment]
#120
