### ISSUE TITLE
Test2: Creating a PR from a GH issue 

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes-sigs/contributor-tweets#49]
Provide the actual tweet content between the commented colons

Hello! This tweet is created from a GH issue, which will be PRed automatically.

**Comment by rajula96reddy** [comment]
@gkarthiks So I tried to test with the label here. but the action  to create a PR wasn't triggered https://github.com/kubernetes-sigs/contributor-tweets/actions/runs/1008990505. I think it might be because, the workflow expects the label as soon as the issue is created. But with the prow bot, we need to add it manually I guess. (Not sure if we can add it by default).
I guess we can add 'issue_comment'  with '\kind tweet' in it as a trigger for the whole workflow? wdyt?

**Comment by gkarthiks** [comment]
You are a little faster in validating :) I am about to make the changes that I mentioned here https://github.com/kubernetes-sigs/contributor-tweets/issues/45#issuecomment-864457008.

Making that PR and this should work after that.

**Comment by gkarthiks** [comment]
@rajula96reddy seems the issue is not created with the proper template in this. The action couldn't able to parse it. 

```
The parsing symbol first found @ -1
```

**Comment by gkarthiks** [comment]
https://github.com/kubernetes-sigs/contributor-tweets/runs/3018378320?check_suite_focus=true#step:5:14

**Comment by chris-short** [comment]
Is it safe to close this?

**Comment by gkarthiks** [comment]
yes. Thank you Chris.
