### ISSUE TITLE
Tweets on Annual community report

### ISSUE THREAD

**Issue by Debanitrkl** [kubernetes-sigs/contributor-tweets#59]
This will feature tweets regarding each specific SIGs requirement as mentioned in the [annual community report](https://www.cncf.io/reports/kubernetes-community-annual-report-2020/) 
```
example: SIG API Machinery:
Performing triage (go to a triage meeting and you’ll see it first hand)
Contributors to the Client Libraries like client-go, python-client
```
There are 30 such tweets with relevant links to be done, and the draft can be found [here](https://docs.google.com/document/d/1YwXC25yVtkfddJj-_2RSLCJFxZkw5H3kvKeSX_DZF5w/edit?usp=sharing)

**Comment by Debanitrkl** [comment]
Looking at the word limit for each tweet, we might require some tweets to be in threads, is that possible with this github-actions
@gkarthiks @palnabarun

**Comment by gkarthiks** [comment]
hi @Debanitrkl , as of now we are using a third party tweet action. It doesn't;t support the threaded model yet.

**Comment by Atharva-Shinde** [comment]
kind/tweet

**Comment by Debanitrkl** [comment]
Yeah good suggestion we can write done against the tweet already tweeted
