### ISSUE TITLE
Help wanted in WG K8s Infra tweet

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes-sigs/contributor-tweets#83]
**Provide the actual tweet content between the commented colons**

WG K8s Infra is looking for contributors to help migrate resources from Google owned infrastructure to community owned, mostly to help with prow jobs. For more information visit: https://github.com/kubernetes/community/tree/master/wg-k8s-infra and https://bit.ly/2Wo6ShX

**Comment by Debanitrkl** [comment]
@sandipanpanda remove the second link that is not required

**Comment by sandipanpanda** [comment]
> @sandipanpanda remove the second link that is not required

I find the linked blog very useful and beginner friendly, especially for new contributors. Will it be a problem if it is kept?

**Comment by sandipanpanda** [comment]
I commented / validate after updating the issue, but it's not getting updated in the PR #84. Yesterday I run / validate after updating the PR and the commmit got force pushed: https://github.com/kubernetes-sigs/contributor-tweets/pull/84#event-5289551302.  There was no issue. Also, I am getting this: https://github.com/kubernetes-sigs/contributor-tweets/actions/runs/1230933687.

**Comment by Debanitrkl** [comment]
> > @sandipanpanda remove the second link that is not required
> 
> I find the linked blog very useful and beginner friendly, especially for new contributors. Will it be a problem if it is kept?

No, it's not a problem I only drafted this tweet and added that link but since characters were increasing so we can put the other link as a thread. Also avoid line breaks and then run /validate it will update fine. It's just a problem with the bot😅

**Comment by sandipanpanda** [comment]
> > > @sandipanpanda remove the second link that is not required
> > 
> > 
> > I find the linked blog very useful and beginner friendly, especially for new contributors. Will it be a problem if it is kept?
> 
> No, it's not a problem I only drafted this tweet and added that link but since characters were increasing so we can put the other link as a thread. Also avoid line breaks and then run /validate it will update fine. It's just a problem with the botsweat_smile

I run / validate after removing the line breaks but it didn't work, the updates to the issue didn't get merged in the tweet PR. The problem: https://github.com/kubernetes-sigs/contributor-tweets/actions/runs/1233540224

I think its better I close this issue and the corresponding PR and make a fresh issue for the tweet.
