### ISSUE TITLE
Auto PR when new blog post comes up 

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes-sigs/contributor-tweets#9]
Do this with GitHub Actions

https://kubernetes.io/blog/

**Comment by mbbroberg** [comment]
Hey @rajula96reddy, I tried to work through a GitHub action here and had no luck. Tagging you in case this is straightforward for you :smile:

**Comment by rajula96reddy** [comment]
Hey @mbbroberg I like this idea. From what I understand, this is same as how we want to extract new posts from `k-dev`. There is an [RSS feed](https://kubernetes.io/feed.xml), which we might have to watch and trigger a tweet. I will take a closer look into this and come up with something.

**Comment by mbbroberg** [comment]
We could get this done with some code to watch for events and trigger a response, but it won't be as simple as installing a GitHub Action.

/remove-lifecycle stale
