### ISSUE TITLE
Help wanted in SIG Usability

### ISSUE THREAD

**Issue by sandipanpanda** [kubernetes-sigs/contributor-tweets#95]
**Provide the actual tweet content between the commented colons**

SIG Usability is currently working on a jobs to be done study and an effort to define universal personas for the upstream project. Welcoming user researchers, designers and new contributors to help. More info in: https://github.com/kubernetes/community/tree/master/sig-usability.

**Comment by Debanitrkl** [comment]
@sandipanpanda we aren't tweeting this now because the first part of the tweet isn't clear yet, we need more information from Sig-Usability.
